version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    user: root
    ports:
      - "5678:5678"
    volumes:
      - ./docker/:/home/node/.n8n
      - ./dist/:/home/node/.n8n/custom/n8n-nodes-galigeo
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin_password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - NODE_ENV=development
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
